language: java
jdk: 
 - openjdk7
 - oraclejdk8

matrix:

# sudo: required


before_script:
  - echo "MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=512m'" > ~/.mavenrc
install:
  - 
#build
script:
  - mvn install
  - mvn site
  
